name: Build Scrcpy Dev (Simple)

on:
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild (-f)'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"

      - name: Build Scrcpy
        run: |
          FORCE_FLAG=""
          if [ "${{ inputs.force_rebuild }}" = "true" ]; then
            FORCE_FLAG="-f"
          fi
          
          # Proste wywołanie. Skrypt zobaczy "sdl3" w build.sh i spróbuje go pobrać z APT.
          ./scripts/run-docker.sh ./build-package.sh -a aarch64 $FORCE_FLAG scrcpy

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scrcpy-dev-package
          path: debs/*.deb
          if-no-files-found: error
